name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint-typecheck-unit:
    name: Lint, typecheck & unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test:unit

  integration:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: "Start X Virtual Frame Buffer"
        run: "echo \"DISPLAY=:99.0\" >> $GITHUB_ENV && Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

      - name: Integration tests (downloads & launches VS Code)
        run: npm test
        timeout-minutes: 30
        shell: bash